In [1]:
import pandas as pd
df=pd.read_excel('file/score.xlsx',index_col='지원번호')

In [5]:
#컬럼 리스트
df.columns
#컬럼 이름
df['이름']
#컬럼이름 다수:리스트 형태로
df[['이름','수학']]
#df['이름':'과학'] #슬라이싱x
df[df.columns[0:4]] #columns 사용해서 슬라이싱 적용
df.loc[:,'이름':'수학'] #loc를 사용해서 슬라이싱 가능

df[df.columns[-1]] #마지막 컬럼 출력
df[df.columns[[0,3,1]]]
df[0:3] #index에 해당되는 3개 출력

지원번호
1번        Python
2번          Java
3번    Javascript
4번           NaN
5번           NaN
6번             C
7번        PYTHON
8번            C#
Name: SW특기, dtype: str

In [9]:
#loc출력-index출력(이름으로 출력)
df.loc['1번']
df.loc[['1번','2번']]
df.loc['1번':'5번']
df.loc['1번','이름':'수학'] #슬라이싱 가능
df.loc['2번':'5번','이름':'수학'] #슬라이싱 가능

       이름   학교    키  국어  영어  수학
지원번호
2번    강태원  구로고  184  40  35  50
3번    강호림  구로고  168  80  75  70
4번    김수찬  구로고  187  40  60  70
5번    김재욱  구로고  188  15  20  10

In [11]:
#iloc출력-리스트 번호로 출력
df.iloc[0]
df.iloc[0:4]
df.iloc[[0,1,5]]
df.iloc[0:4,1:5]

       학교    키  국어  영어
지원번호
1번    구로고  197  90  85
2번    구로고  184  40  35
3번    구로고  168  80  75
4번    구로고  187  40  60

In [12]:
df['키']

지원번호
1번    197
2번    184
3번    168
4번    187
5번    188
6번    202
7번    188
8번    190
Name: 키, dtype: int64

In [13]:
df[df['키']>185]

       이름    학교    키   국어   영어   수학  과학  사회    SW특기
지원번호
1번    강나래   구로고  197   90   85  100  95  85  Python
4번    김수찬   구로고  187   40   60   70  75  80     NaN
5번    김재욱   구로고  188   15   20   10  35  10     NaN
6번    박동현  디지털고  202   80  100   95  85  80       C
7번    박혜정  디지털고  188   55   65   45  40  35  PYTHON
8번    승근열  디지털고  190  100   85   90  95  95      C#

In [14]:
#조건: True,False

df[df['국어']>70]

       이름    학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    강나래   구로고  197   90   85  100  95  85      Python
3번    강호림   구로고  168   80   75   70  80  75  Javascript
6번    박동현  디지털고  202   80  100   95  85  80           C
8번    승근열  디지털고  190  100   85   90  95  95          C#