In [11]:
import pandas as pd
import numpy as np
df=pd.read_excel('file/score.xlsx',index_col='지원번호')

In [9]:
df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    강나래   구로고  197   90   85  100  95  85      Python
2번    강태원   구로고  184   40   35   50  55  25        Java
3번    강호림   구로고  168   80   75   70  80  75  Javascript
4번    김수찬   구로고  187   40   60   70  75  80          없음
5번    김재욱   구로고  188   15   20   10  35  10          없음
6번    박동현  디지털고  202   80  100   95  85  80           C
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON
8번    승근열  디지털고  190  100   85   90  95  95          C#

In [ ]:
# #Nan데이터 처리 - 결축치
#numpy는 숫자만 가능, 문자가 안됨.
#np.nan: 명령어 numpy-non 데이터 모두 입력
# #fillna:nan데이터 채워줌
# # df.fillna(' ',inplace=True)

df['학교'] = np.nan
df

       이름  학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    강나래 NaN  197   90   85  100  95  85      Python
2번    강태원 NaN  184   40   35   50  55  25        Java
3번    강호림 NaN  168   80   75   70  80  75  Javascript
4번    김수찬 NaN  187   40   60   70  75  80         NaN
5번    김재욱 NaN  188   15   20   10  35  10         NaN
6번    박동현 NaN  202   80  100   95  85  80           C
7번    박혜정 NaN  188   55   65   45  40  35      PYTHON
8번    승근열 NaN  190  100   85   90  95  95          C#

In [18]:
#dropna: nan 데이터 삭제 
df=pd.read_excel('file/score.xlsx',index_col='지원번호')
# df.dropna(inplace=True)
#axis: index-가로  ,columns-세로 /  how: any-1개만 있어도, all-모두 있어야
# df.dropna(axis='index',how='any') 
df.dropna(axis='columns',how='any')

       이름    학교    키   국어   영어   수학  과학  사회
지원번호
1번    강나래   구로고  197   90   85  100  95  85
2번    강태원   구로고  184   40   35   50  55  25
3번    강호림   구로고  168   80   75   70  80  75
4번    김수찬   구로고  187   40   60   70  75  80
5번    김재욱   구로고  188   15   20   10  35  10
6번    박동현  디지털고  202   80  100   95  85  80
7번    박혜정  디지털고  188   55   65   45  40  35
8번    승근열  디지털고  190  100   85   90  95  95